# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
    ]
