# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171021_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductClass',
            new_name='ProductType',
        ),
    ]
